library("monocle")
library(reshape)
setwd("~/MyeloidCSVs")
exprs_matrix <- read.table("exprs.csv",sep=",",header=T,row.names=1)
phenoData_matrix <- read.delim("phenoData.csv",sep=",",row.names=1)
featureData_matrix <- read.delim("featureData.csv",sep=",",row.names=1)
pd <- new("AnnotatedDataFrame", data = phenoData_matrix)
fd <- new("AnnotatedDataFrame", data = featureData_matrix)
MacData <- newCellDataSet(as.matrix(exprs_matrix), phenoData = pd, featureData = fd)
MacData <- newCellDataSet(as.matrix(exprs_matrix), phenoData = pd, featureData = fd,expressionFamily=negbinomial.size())
MacData <- estimateSizeFactors(MacData)
MacData <- estimateDispersions(MacData)
MacData <- detectGenes(MacData, min_expr = 0.1)
expressed_genes <- row.names(subset(fData(MacData),num_cells_expressed >= 10))
diff_test_res <- differentialGeneTest(MacData[expressed_genes,],fullModelFormulaStr = "~Phenotype")
ordering_genes <- row.names (subset(diff_test_res, qval < 1))
MacData <- setOrderingFilter(MacData, ordering_genes)
MacData <- reduceDimension(MacData, max_components = 2,method = 'DDRTree')
MacData <- orderCells(MacData)
plot_cell_trajectory(MacData, color_by = 'as.factor(Phenotype)',cell_size=1)