setwd("~/AstrocyteCSVs")
library(phateR)
library(ggplot2)
library(readr)
library(viridis)
library(jcolors)
library(Rmagic)
LesionData <- read.csv("AstrocytesPHATE.csv")
ClusterData <- read.csv("AstrocyteClusters.csv")
LesionData_PHATE <- phate(LesionData,k=100)
Clusters <- factor(ClusterData$Phenotype)
PhatePlot <- ggplot(LesionData_PHATE)+geom_point(aes(x=PHATE1, y=PHATE2, color=Clusters))+labs(color="Phenotype")+scale_color_jcolors(palette = "rainbow")
plot(PhatePlot)